### PR TITLE
fix: Add OPUS_SET_VBR, so we can disable it

### PR DESCRIPTION
**Pull request by Green-Sky**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/hs-tokstyle/254)

### CODE REVIEW

**Review by nurupo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/hs-tokstyle/254)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Comment by Green-Sky** [comment]
the code (cache?) server seems to be down

**Comment by nurupo** [comment]
This bazel failure is @iphy's area of expertise.

I have looked into it myself, but I'm not sure why bazel fails. The cache seems to be up, I'm able to ping it on port 9092 via curl HTTP GET -- it returns some sort of a binary back, so the service is running. It's supposed to be gRPC instead of HTTP, so the binary output makes sense.

The "domain/ip:port" address format in the bazel exception output is kind of weird, if it was an HTTP GET, that would do a GET on /ip:port of the domain, but that could also be just how it prints out the address.

**Comment by iphydf** [comment]
You can merge now. I've made bazel optional.

**Comment by Green-Sky** [comment]
merged, thanks

**Pull request merged**
